config/routes.rb
Rails.application.routes.draw do
 	

 	root 'home#index'

 	resources 'crypto'
 	resources 'movies'

  get '/movies', to: 'home#movie'
  get '/mails', to: 'home#mail'
  get '/value', to: 'home#value'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptomoney.rb
class Cryptomoney < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crypto_controller.rb
class CryptoController < ApplicationController
 

  def new
  	@crypto = Cryptomoney.new

  	if Cryptomoney.all == nil
  	 StartScrap.new.perform
    else
     Cryptomoney.delete_all
     StartScrap.new.perform
    end

  	@crypto_all = Cryptomoney.all
  end

  def create
  	@crypto_name = params[:cryptomoney][:name]
  	puts @crypto_name
  	@crypto_value = Cryptomoney.find_by_name("#{@crypto_name}").value
  end

  def show
  	@value = Cryptomoney.id.value
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  end

  def create
  	@movie_name = params[:movie][:name]
  	SearchMovies.new(@movie_name).perform
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/crypto/create.html.erb
<p> The value of <%= @crypto_name %> is <%= @crypto_value %> </p>

app/views/crypto/new.html.erb
<div class="colonne"> 


<%= form_for( @crypto,  url: crypto_index_path) do |f| %>
 
  	<div class="field">
    	<%= f.label :name %><br />
    	<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  	</div>
	<% end %>



	<% @crypto_all.each do |x| %>
		<div class="list"><%= x.name %></div>
		</br>
	<%end %>

</div>

app/views/crypto/show.html.erb
<p> The value of <%= @crypto_name %> is <%= @crypto_value %> </p>

app/views/home/index.html.erb
<h1>bienvenue</h1>
<%= link_to "Crypto app", new_crypto_path %>
<%= link_to "Movie app",  movies_path %>
<a href="/mail">Mails app</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SrapMovieMail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/create.html.erb
<%= @array_page %>

app/views/movies/index.html.erb
<%= form_for( :movie,  url: movies_path) do |f| %>
 
  	<div class="field">
    	<%= f.label :name %><br />
    	<%= f.text_field :name, autofocus: true, autocomplete: "movie name" %>
  	</div>
<% end %>

app/views/movies/new.html.erb
<%= form_for( :movie,  url: movies_path) do |f| %>
 
  	<div class="field">
    	<%= f.label :name %><br />
    	<%= f.text_field :name, autofocus: true, autocomplete: "movie name" %>
  	</div>
<% end %>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>